[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\slsc_12201_custom_device'

[projects.cd]
path = 'Source\SLSC-12201 DIO.lvproj'

[[build.steps]]
name = 'Build SLSC-12201 DIO Custom Device'
type = 'lvBuildAll'
project = '{cd}'

[package]
type = 'nipkg'
payload_dir = 'Built'
install_destination = 'documents\\National Instruments\\NI VeriStand {veristand_version}\\SLSC Plugins\\Modules'

[notification]
type = 'teams'
